// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlbizrlwcweaxcyukwgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsYml6cmx3Y3dlYXhjeXVrd2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzA0ODAsImV4cCI6MjA2NDI0NjQ4MH0.SfHyHsIQ-E7EpCZfQmv-Q9fNylJ2AwsfwikbQZRuSSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);